### ISSUE TITLE
unable to import pypat (getting errors)

### ISSUE THREAD

**Issue by dahmadjid** [tnewman/pat#43]
got the following error when importing pypat using anaconda environment 
`import _pypat`
`Exception: Could not open audio device. Audio playback is unsupported on this`
when i use normal python3 with terminal i get this:
`import _pypat`
`ImportError: /lib/x86_64-linux-gnu/librsvg-2.so.2: undefined symbol: cairo_tag_end`
I have made sure I have SDL2,ffmpeg installed. what could've caused this ?
my code is simply `import pypat`

Edit: It would be better for me if i can solve this for anaconda.

**Comment by tnewman** [comment]
What distro are you running? I would like to see if I can replicate and fix this.

**Comment by dahmadjid** [comment]
i used Linux Lite 5.0 (ubuntu 20.04 based distro). Im currently gonna try the same in manjaro or ubuntu directly and see how it goes

**Comment by tnewman** [comment]
I never tested on 20.04, but I would like it to be compatible. Let me know what you find.

**Comment by tnewman** [comment]
I installed Ubuntu 20.04 from scratch. I was able to play https://dl.espressif.com/dl/audio/ff-16b-2c-44100hz.aac using the following steps:

1. Install dependencies from the readme:
    ```bash
    sudo apt install build-essential libavutil-dev libswresample-dev libavdevice-dev libavcodec-dev libavformat-dev libswscale-dev libsdl2-dev
    ```
2. Install pypat:
    ```bash
    sudo pip3 install pypat
    ```
3. Run the following test code:
    ```python
    import pypat
    pypat.play('https://dl.espressif.com/dl/audio/ff-16b-2c-44100hz.aac')
    ```

Is this similar to what you did?

**Comment by tnewman** [comment]
@dahmadjid, may I close this ticket? I need more information to be able to work on it.

**Comment by tnewman** [comment]
Please create a new issue if you would like to investigate this further.
